name: Build MAUI APK and Release

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: windows-latest

    env:
      PROJECT_PATH: Sources/MedicalScanner.csproj

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Bump version in .csproj
        id: bump_version
        run: |
          VERSION_FILE="$PROJECT_PATH"
          OLD_VERSION=$(grep -oP '(?<=<ApplicationVersion>).*?(?=</ApplicationVersion>)' "$VERSION_FILE" || echo "1.0.0")
          OLD_CODE=$(grep -oP '(?<=<ApplicationDisplayVersion>).*?(?=</ApplicationDisplayVersion>)' "$VERSION_FILE" || echo "1")
          NEW_CODE=$((OLD_CODE + 1))
          NEW_VERSION="1.0.$NEW_CODE"

          echo "Bumping version to $NEW_VERSION ($NEW_CODE)"
          sed -i "s|<ApplicationVersion>.*</ApplicationVersion>|<ApplicationVersion>$NEW_VERSION</ApplicationVersion>|g" "$VERSION_FILE"
          sed -i "s|<ApplicationDisplayVersion>.*</ApplicationDisplayVersion>|<ApplicationDisplayVersion>$NEW_CODE</ApplicationDisplayVersion>|g" "$VERSION_FILE"

          echo "version_name=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_code=$NEW_CODE" >> $GITHUB_OUTPUT

      - name: Restore and build
        run: |
          dotnet restore $PROJECT_PATH
          dotnet build $PROJECT_PATH -c Release -f:net8.0-android

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*.apk" | grep bin/Release | head -n1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.bump_version.outputs.version_name }}"
          tag_name: "v${{ steps.bump_version.outputs.version_name }}"
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}